development:
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  secret_key_base: 9adf6cf4c3e4198b090550e7666004ffd32f5020b7801e2b5da2982b25f11f06eeec8f0543205fe5c749d2f8cb983377b266ac03167db19c384b2c0cd8ed360b

test:
  secret_key_base: 404f09a59d156324c5f0644785c02a39b8f8b423e7ac398e9382b76bec0e978cfb7c1c5e1b501487a35db19b608975273c33a596080f12de76712dacd9ecb65b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>